package com.example.core.contract

/**
 * Contract status definition based on Master Development Contract Section 3.
 *
 * Rule: JANGAN PERNAH mengubah IMPLEMENTED menjadi PRODUCTION_READY tanpa bukti pengujian.
 */
enum class FeatureStatus {
  NOT_STARTED,
  IMPLEMENTING,
  IMPLEMENTED,
  SOURCE_IMPLEMENTED,
  UNIT_TEST_VERIFIED,
  BUILD_VERIFIED,
  RUNTIME_VERIFIED,
  DATA_VERIFIED,
  PRODUCTION_READY,
  BLOCKED,
  REAL_DEVICE_VERIFICATION_PENDING,
  REAL_DEVICE_VERIFIED,
  LIVE_API_NOT_VERIFIED,
  LIVE_API_VERIFIED,
  APK_VERIFIED,
  LIVE_DATA_VERIFIED,
  DATA_PROCESSING_VERIFIED,
  MARKERS_VERIFIED
}
